import Link from "next/link";
import { ArrowUpRight, ChevronRight, Clock3, Database, ListFilter, Sparkles, TrendingUp } from "lucide-react";
import { RevenueChart } from "@/components/charts";
import { customers, formatCurrency, orders, revenueByMonth } from "@/lib/data/demo-data";

const completedOrders = orders.filter((order) => order.status === "completed");
const totalRevenue = completedOrders.reduce((sum, order) => sum + order.amount, 0);
const customerRevenue = customers.map((customer) => ({ ...customer, revenue: completedOrders.filter((order) => order.customer_id === customer.id).reduce((sum, order) => sum + order.amount, 0) })).sort((a, b) => b.revenue - a.revenue);
const runs = [{ id: "run_8f21", question: "Which customers generated the most revenue?", time: "2 min ago", duration: "0.65s" }, { id: "run_8f14", question: "How has revenue changed over time?", time: "Yesterday", duration: "0.74s" }, { id: "run_8e92", question: "Which products are performing best?", time: "Sep 18, 2024", duration: "0.68s" }];

function KpiCard({ label, value, change, icon: Icon }: { label: string; value: string; change: string; icon: typeof TrendingUp }) {
  return <div className="rounded-[10px] border border-[#e4e8eb] bg-white p-5 shadow-[0_2px_5px_rgba(26,40,51,0.02)]"><div className="flex items-center justify-between"><span className="text-[12px] font-medium text-[#75808a]">{label}</span><span className="grid h-7 w-7 place-items-center rounded-[7px] bg-[#edf6f2] text-[#347d69]"><Icon size={15} /></span></div><div className="mt-3 text-[25px] font-semibold tracking-[-0.04em] text-[#1c2932]">{value}</div><div className="mt-2 flex items-center gap-1 text-[11px] text-[#3c8b6e]"><ArrowUpRight size={13} />{change}<span className="text-[#98a1a8]">vs last period</span></div></div>;
}

export function Dashboard() {
  return <div className="space-y-7">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.13em] text-[#34806c]">Overview</p><h1 className="text-[29px] font-semibold tracking-[-0.04em] text-[#1c2932]">AI Data Agent</h1><p className="mt-2 text-[13px] text-[#79848d]">A clear view of what is happening across your business data.</p></div><Link href="/ask-data" className="inline-flex w-fit items-center gap-2 rounded-[7px] bg-[#1e5d50] px-3.5 py-2.5 text-[12px] font-semibold text-white shadow-sm transition hover:bg-[#174a40]"><Sparkles size={15} />Ask your data</Link></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Total revenue" value={formatCurrency(totalRevenue)} change="12.8%" icon={TrendingUp} /><KpiCard label="Customers" value={customers.length.toLocaleString()} change="8.4%" icon={Database} /><KpiCard label="Orders" value={completedOrders.length.toLocaleString()} change="16.2%" icon={ListFilter} /><KpiCard label="Average order value" value={formatCurrency(totalRevenue / completedOrders.length)} change="4.6%" icon={TrendingUp} /></div>
    <div className="grid gap-5 xl:grid-cols-[1.5fr_1fr]"><section className="rounded-[10px] border border-[#e4e8eb] bg-white p-5 shadow-[0_2px_5px_rgba(26,40,51,0.02)]"><div className="flex items-start justify-between"><div><h2 className="text-[14px] font-semibold text-[#29343d]">Revenue performance</h2><p className="mt-1 text-[11px] text-[#8a949c]">Completed revenue across the last 12 months</p></div><button className="flex items-center gap-1 text-[11px] font-medium text-[#6e7a83]">Last 12 months <ChevronRight size={13} /></button></div><div className="mt-5 h-[265px]"><RevenueChart data={revenueByMonth} /></div></section><section className="rounded-[10px] border border-[#e4e8eb] bg-white p-5 shadow-[0_2px_5px_rgba(26,40,51,0.02)]"><div className="flex items-start justify-between"><div><h2 className="text-[14px] font-semibold text-[#29343d]">Top customers</h2><p className="mt-1 text-[11px] text-[#8a949c]">By completed revenue</p></div><Link href="/ask-data" className="text-[11px] font-medium text-[#34806c]">Ask more</Link></div><div className="mt-4 divide-y divide-[#eef0f1]">{customerRevenue.slice(0, 5).map((customer, index) => <div key={customer.id} className="flex items-center justify-between py-3"><div className="flex min-w-0 items-center gap-3"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-[#edf4f1] text-[10px] font-semibold text-[#377866]">{index + 1}</span><div className="min-w-0"><p className="truncate text-[12px] font-medium text-[#38444d]">{customer.name}</p><p className="mt-0.5 truncate text-[10px] text-[#90999f]">{customer.industry}</p></div></div><span className="text-[12px] font-semibold text-[#354149]">{formatCurrency(customer.revenue)}</span></div>)}</div></section></div>
    <section className="rounded-[10px] border border-[#e4e8eb] bg-white shadow-[0_2px_5px_rgba(26,40,51,0.02)]"><div className="flex items-center justify-between border-b border-[#edf0f1] px-5 py-4"><div><h2 className="text-[14px] font-semibold text-[#29343d]">Recent agent runs</h2><p className="mt-1 text-[11px] text-[#8a949c]">Questions answered by DataPilot</p></div><Link href="/agent-runs" className="flex items-center gap-1 text-[11px] font-medium text-[#34806c]">View all <ChevronRight size={13} /></Link></div><div className="divide-y divide-[#eef0f1]">{runs.map((run) => <Link href={`/agent-runs?run=${run.id}`} key={run.id} className="flex flex-col gap-2 px-5 py-3.5 transition hover:bg-[#fafcfb] sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#edf6f2] text-[#36806d]"><Sparkles size={13} /></span><div><p className="text-[12px] font-medium text-[#3b4750]">{run.question}</p><p className="mt-0.5 text-[10px] text-[#9aa2a8]">{run.id} · {run.time}</p></div></div><div className="flex items-center gap-3 pl-10 text-[11px] text-[#89939a] sm:pl-0"><span className="flex items-center gap-1"><Clock3 size={12} />{run.duration}</span><span className="rounded-full bg-[#eaf6ef] px-2 py-1 text-[10px] font-semibold text-[#34815e]">Completed</span></div></Link>)}</div></section>
  </div>;
}
