"use client";

import { Check, ChevronRight, Database, FileCode2, LockKeyhole, RefreshCw, Server, ShieldCheck, Table2 } from "lucide-react";
import type { AgentRun } from "@/types";

export const demoRuns: AgentRun[] = [
  { id: "run_8f21", question: "Which customers generated the most revenue?", answer: "Northstar Health generated the most revenue at $27,710.", sql: "SELECT c.name, SUM(o.amount) AS revenue FROM orders o JOIN customers c ON c.id = o.customer_id WHERE o.status = 'completed' GROUP BY c.id, c.name ORDER BY revenue DESC LIMIT 10;", steps: [], data: [], visualization: { type: "bar", title: "Top customers by revenue" }, metadata: { durationMs: 654, rowsReturned: 10, tables: ["orders", "customers"] }, createdAt: "2 min ago", status: "Completed" },
  { id: "run_8f14", question: "How has revenue changed over time?", answer: "Revenue grew steadily across the year, finishing strongest in December.", sql: "SELECT DATE_TRUNC('month', created_at) AS month, SUM(amount) AS revenue FROM orders WHERE status = 'completed' GROUP BY 1 ORDER BY 1;", steps: [], data: [], visualization: { type: "line", title: "Revenue by month" }, metadata: { durationMs: 742, rowsReturned: 12, tables: ["orders"] }, createdAt: "Yesterday", status: "Completed" },
  { id: "run_8e92", question: "Which products are performing best?", answer: "Insight Pro is the strongest product in the demo dataset.", sql: "SELECT p.name, SUM(o.amount) AS revenue FROM orders o JOIN products p ON p.id = o.product_id WHERE o.status = 'completed' GROUP BY p.name ORDER BY revenue DESC;", steps: [], data: [], visualization: { type: "bar", title: "Revenue by product" }, metadata: { durationMs: 681, rowsReturned: 6, tables: ["orders", "products"] }, createdAt: "Sep 18, 2024", status: "Completed" },
];

export function DataSources() { return <div className="space-y-7"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.13em] text-[#34806c]">Data Sources</p><h1 className="text-[29px] font-semibold tracking-[-0.04em] text-[#1c2932]">Your data, connected</h1><p className="mt-2 text-[13px] text-[#79848d]">Manage the sources DataPilot can inspect and query.</p></div><section className="max-w-[780px] rounded-[10px] border border-[#e4e8eb] bg-white p-6 shadow-[0_2px_5px_rgba(26,40,51,0.02)]"><div className="flex flex-col justify-between gap-4 border-b border-[#edf0f1] pb-5 sm:flex-row sm:items-start"><div className="flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-[9px] bg-[#e8f3ef] text-[#2c745f]"><Database size={19} /></span><div><h2 className="text-[15px] font-semibold text-[#29343d]">Production analytics database</h2><p className="mt-1 text-[11px] text-[#929ba1]">PostgreSQL · Demo connection</p></div></div><span className="flex w-fit items-center gap-1.5 rounded-full bg-[#e9f6ee] px-2.5 py-1.5 text-[10px] font-semibold text-[#34815e]"><span className="h-1.5 w-1.5 rounded-full bg-[#42aa76]" />Connected</span></div><div className="grid gap-4 py-5 sm:grid-cols-2"><Info icon={Server} label="Engine" value="PostgreSQL 15" /><Info icon={RefreshCw} label="Last synchronized" value="Today at 09:42 UTC" /><Info icon={LockKeyhole} label="Access mode" value="Read-only" /><Info icon={ShieldCheck} label="Environment" value="Demo data" /></div><div className="rounded-[8px] border border-[#e9eeeb] bg-[#f8fbf9] p-4"><div className="flex items-center gap-2"><Table2 size={14} className="text-[#4b8b76]" /><span className="text-[11px] font-semibold text-[#47695e]">Available tables</span></div><div className="mt-3 flex flex-wrap gap-2">{["customers", "products", "orders"].map((table) => <span key={table} className="rounded-[5px] border border-[#d9e8e1] bg-white px-2.5 py-1.5 font-mono text-[10px] text-[#51786b]">{table}</span>)}</div></div><div className="mt-5 flex items-center gap-2 text-[10px] text-[#98a19f]"><ShieldCheck size={13} className="text-[#5e9e88]" />Demo data is local and contains no production credentials or customer information.</div></section></div>; }
function Info({ icon: Icon, label, value }: { icon: typeof Server; label: string; value: string }) { return <div className="flex items-center gap-2.5"><Icon size={15} className="text-[#8aa69b]" /><div><p className="text-[10px] text-[#9aa2a7]">{label}</p><p className="mt-0.5 text-[12px] font-medium text-[#526069]">{value}</p></div></div>; }

export function AgentRuns() { return <div className="space-y-7"><div><p className="mb-2 text-[11px] font-semibold uppercase tracking-[0.13em] text-[#34806c]">Agent Runs</p><h1 className="text-[29px] font-semibold tracking-[-0.04em] text-[#1c2932]">A history of your questions</h1><p className="mt-2 text-[13px] text-[#79848d]">Review queries, execution traces, and the answers DataPilot generated.</p></div><section className="overflow-hidden rounded-[10px] border border-[#e4e8eb] bg-white shadow-[0_2px_5px_rgba(26,40,51,0.02)]"><div className="flex items-center justify-between border-b border-[#edf0f1] px-5 py-4"><span className="text-[12px] font-semibold text-[#46525a]">Recent runs <span className="ml-1 font-normal text-[#9aa2a7]">{demoRuns.length}</span></span><span className="rounded-[5px] border border-[#e4e8eb] px-2 py-1 text-[10px] text-[#89939a]">All runs</span></div><div className="hidden grid-cols-[110px_1fr_130px_100px_25px] gap-4 border-b border-[#edf0f1] bg-[#fbfcfc] px-5 py-3 text-[10px] font-semibold uppercase tracking-[0.08em] text-[#9ba3a8] sm:grid"><span>Run ID</span><span>Question</span><span>Status</span><span>Time</span><span /></div>{demoRuns.map((run) => <div key={run.id} className="grid gap-2 border-b border-[#edf0f1] px-5 py-4 last:border-0 sm:grid-cols-[110px_1fr_130px_100px_25px] sm:items-center sm:gap-4"><span className="font-mono text-[10px] text-[#8b969d]">{run.id}</span><div><p className="text-[12px] font-medium text-[#45525b]">{run.question}</p><p className="mt-1 text-[10px] text-[#a0a8ad] sm:hidden">{run.createdAt} · {run.metadata.durationMs}ms</p></div><span className="flex w-fit items-center gap-1.5 rounded-full bg-[#eaf6ef] px-2 py-1 text-[10px] font-semibold text-[#34815e]"><Check size={11} />{run.status}</span><span className="hidden text-[11px] text-[#8d979e] sm:block">{run.createdAt}</span><ChevronRight size={15} className="hidden text-[#a3adb2] sm:block" /></div>)}</section><div className="flex items-center gap-2 text-[11px] text-[#929ba0]"><FileCode2 size={14} className="text-[#78a291]" />Each run uses read-only SQL validation before execution.</div></div>; }
